//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrative.Lara {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integrative.Lara.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle detected: modification handlers should not modify the source data..
        /// </summary>
        internal static string BindingCycleDetected {
            get {
                return ResourceManager.GetString("BindingCycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an element inside itself..
        /// </summary>
        internal static string CannotAddInsideItself {
            get {
                return ResourceManager.GetString("CannotAddInsideItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove from parent, the node has no parent element..
        /// </summary>
        internal static string CannotRemoveNoParent {
            get {
                return ResourceManager.GetString("CannotRemoveNoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tag name. It needs to have a &apos;-&apos; and cannot have spaces..
        /// </summary>
        internal static string DashRequired {
            get {
                return ResourceManager.GetString("DashRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;EventName&apos; property cannot be null or empty..
        /// </summary>
        internal static string EventNameNull {
            get {
                return ResourceManager.GetString("EventNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlushPartialChanges() method is available only for events declared with the option LongRunnning = true..
        /// </summary>
        internal static string FlushNotAvailable {
            get {
                return ResourceManager.GetString("FlushNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the focus() method, first add the element to a document..
        /// </summary>
        internal static string FocusDisconnected {
            get {
                return ResourceManager.GetString("FocusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 403: Forbidden..
        /// </summary>
        internal static string Http403 {
            get {
                return ResourceManager.GetString("Http403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component types must inherit from the Component class..
        /// </summary>
        internal static string MustInherit {
            get {
                return ResourceManager.GetString("MustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current document..
        /// </summary>
        internal static string NoCurrentDocument {
            get {
                return ResourceManager.GetString("NoCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current session..
        /// </summary>
        internal static string NoCurrentSession {
            get {
                return ResourceManager.GetString("NoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid child/parent nodes specified..
        /// </summary>
        internal static string NodeNotFoundInsideParent {
            get {
                return ResourceManager.GetString("NodeNotFoundInsideParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference before/after node not found..
        /// </summary>
        internal static string ReferenceNodeNotFound {
            get {
                return ResourceManager.GetString("ReferenceNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal error or misconfiguration and was unable to complete your request..
        /// </summary>
        internal static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerEvent already disposed..
        /// </summary>
        internal static string ServerEventAlreadyDisposed {
            get {
                return ResourceManager.GetString("ServerEventAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server events are not enabled. Call ServerEventsOn() in order to use ServerEventFlush()..
        /// </summary>
        internal static string ServerEventsNotEnabled {
            get {
                return ResourceManager.GetString("ServerEventsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;slot&apos; attribute can only be modified on elements not yet attached to a parent..
        /// </summary>
        internal static string SlotOnlyParent {
            get {
                return ResourceManager.GetString("SlotOnlyParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the address for the web service..
        /// </summary>
        internal static string SpecifyAddressService {
            get {
                return ResourceManager.GetString("SpecifyAddressService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the method for the web service (e.g. &apos;POST&apos;)..
        /// </summary>
        internal static string SpecifyMethodService {
            get {
                return ResourceManager.GetString("SpecifyMethodService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element tag names cannot contain spaces..
        /// </summary>
        internal static string TagNameSpaces {
            get {
                return ResourceManager.GetString("TagNameSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many Pop() calls..
        /// </summary>
        internal static string TooManyPops {
            get {
                return ResourceManager.GetString("TooManyPops", resourceCulture);
            }
        }
    }
}
