//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrative.Lara {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Integrative.Lara.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AutocompleteNullProvider {
            get {
                return ResourceManager.GetString("AutocompleteNullProvider", resourceCulture);
            }
        }
        
        internal static string AutocompleteOrphan {
            get {
                return ResourceManager.GetString("AutocompleteOrphan", resourceCulture);
            }
        }
        
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        internal static string BindingCycleDetected {
            get {
                return ResourceManager.GetString("BindingCycleDetected", resourceCulture);
            }
        }
        
        internal static string BrowserAppConnectionRejected {
            get {
                return ResourceManager.GetString("BrowserAppConnectionRejected", resourceCulture);
            }
        }
        
        internal static string CannotAddInsideItself {
            get {
                return ResourceManager.GetString("CannotAddInsideItself", resourceCulture);
            }
        }
        
        internal static string CannotRemoveNoParent {
            get {
                return ResourceManager.GetString("CannotRemoveNoParent", resourceCulture);
            }
        }
        
        internal static string DashRequired {
            get {
                return ResourceManager.GetString("DashRequired", resourceCulture);
            }
        }
        
        internal static string EventNameNull {
            get {
                return ResourceManager.GetString("EventNameNull", resourceCulture);
            }
        }
        
        internal static string FlushNotAvailable {
            get {
                return ResourceManager.GetString("FlushNotAvailable", resourceCulture);
            }
        }
        
        internal static string FocusDisconnected {
            get {
                return ResourceManager.GetString("FocusDisconnected", resourceCulture);
            }
        }
        
        internal static string Http403 {
            get {
                return ResourceManager.GetString("Http403", resourceCulture);
            }
        }
        
        internal static string InputElementNull {
            get {
                return ResourceManager.GetString("InputElementNull", resourceCulture);
            }
        }
        
        internal static string InvalidBindingExpression {
            get {
                return ResourceManager.GetString("InvalidBindingExpression", resourceCulture);
            }
        }
        
        internal static string InvalidTagName {
            get {
                return ResourceManager.GetString("InvalidTagName", resourceCulture);
            }
        }
        
        internal static string MustInherit {
            get {
                return ResourceManager.GetString("MustInherit", resourceCulture);
            }
        }
        
        internal static string NoCurrentContext {
            get {
                return ResourceManager.GetString("NoCurrentContext", resourceCulture);
            }
        }
        
        internal static string NoCurrentDocument {
            get {
                return ResourceManager.GetString("NoCurrentDocument", resourceCulture);
            }
        }
        
        internal static string NoCurrentPage {
            get {
                return ResourceManager.GetString("NoCurrentPage", resourceCulture);
            }
        }
        
        internal static string NoCurrentService {
            get {
                return ResourceManager.GetString("NoCurrentService", resourceCulture);
            }
        }
        
        internal static string NoCurrentSession {
            get {
                return ResourceManager.GetString("NoCurrentSession", resourceCulture);
            }
        }
        
        internal static string NodeNotFoundInsideParent {
            get {
                return ResourceManager.GetString("NodeNotFoundInsideParent", resourceCulture);
            }
        }
        
        internal static string ReferenceNodeNotFound {
            get {
                return ResourceManager.GetString("ReferenceNodeNotFound", resourceCulture);
            }
        }
        
        internal static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        internal static string ServerEventAlreadyDisposed {
            get {
                return ResourceManager.GetString("ServerEventAlreadyDisposed", resourceCulture);
            }
        }
        
        internal static string ServerEventsNotEnabled {
            get {
                return ResourceManager.GetString("ServerEventsNotEnabled", resourceCulture);
            }
        }
        
        internal static string SlotOnlyParent {
            get {
                return ResourceManager.GetString("SlotOnlyParent", resourceCulture);
            }
        }
        
        internal static string SpecifyAddressService {
            get {
                return ResourceManager.GetString("SpecifyAddressService", resourceCulture);
            }
        }
        
        internal static string SpecifyMethodService {
            get {
                return ResourceManager.GetString("SpecifyMethodService", resourceCulture);
            }
        }
        
        internal static string TagNameSpaces {
            get {
                return ResourceManager.GetString("TagNameSpaces", resourceCulture);
            }
        }
        
        internal static string TooManyPops {
            get {
                return ResourceManager.GetString("TooManyPops", resourceCulture);
            }
        }
        
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
    }
}
